---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - python
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
      - TODOC
  radon:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.py"
exclude_paths: [".__stash__"]
