sudo: false
language: python
python:
  - "nightly"
  - "3.5-dev"
  - "3.5"
  - "3.2"
  - "3.3"
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy3"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install codecov 
# command to run tests
script: py.test

#install: pip install tox
#script: tox

notifications:
  email: true

after_success:
  - codecov -e tests/

cache:
  directories:
    - $HOME/.cache/pip/wheels

branches:
  only:
  - master
